routes:
    test_route26:
        controller:  \ExampleCo\Example\ExampleController:testAction
        route: /test
        methods: GET
        middleware:
            authentication:
                class: \ExampleCo\Example\ExampleRouteMiddleware:a12n
                params:
                    test1: 1
                    test2: 2
            other2:
                class: \ExampleCo\Example\ExampleRouteMiddleware::other
                params:
                    test5: 5
                    test6: 6
            

groups:
    api:
        route: /api
        group:
            test:
                route: /test
                methods:    GET|POST
                controller: \ExampleCo\Example\ExampleController:getOrPostTestAction
            test2:
                route: /test2
                group:
                    test_sub:
                        route:  /test-sub
                        methods:    GET
                        controller: \ExampleCo\Example\ExampleController:subAction
